### ISSUE TITLE
BrickShape.ttl targetSubjectsOf

### ISSUE THREAD

**Issue by purringeagle** [BrickSchema/py-brickschema#61]
Just wondering for something like the following constraint in the BrickShape.ttl:

```
bsh:hasLocationRangeShape a sh:NodeShape ;
    sh:property [ sh:class brick:Location ;
            sh:message "Property hasLocation has object with incorrect type" ;
            sh:path brick:hasLocation ] ;
    sh:targetSubjectsOf brick:hasLocation 
```

Should "sh:targetSubjectsOf" be "sh:targetObjectsOf" instead?

(Similarly for other object constraints.)

Edit:
It seems that the default brick shapes are not loaded in Graph.validate:
```
      def validate(self, shape_graphs=None, default_brick_shapes=True):
        """
        Validates the graph using the shapes embedded w/n the graph. Optionally loads in normative Brick shapes
        and externally defined shapes

        Args:
          shape_graphs (list of rdflib.Graph or brickschema.graph.Graph): merges these graphs and includes them in
                the validation
          default_brick_shapes (bool): if True, loads in the default Brick shapes packaged with brickschema

        Returns:
          (conforms, resultsGraph, resultsText) from pyshacl
        """
        shapes = None
        if shape_graphs is not None and isinstance(shape_graphs, list):
            shapes = functools.reduce(lambda x, y: x + y, shape_graphs)
        return pyshacl.validate(self, shacl_graph=shapes)
```

Is that intentional or perhaps work in progress?

**Comment by gtfierro** [comment]
Hi @purringeagle !

I'm pretty sure the shapes are correctly phrased, but let's walk through it.

`targetSubjectsOf` will bind the shape to all entities which have a `hasLocation` relationship to another entity. The `sh:property` component of the NodeShape verifies that the type of the values of the `hasLocation` relationship are indeed instances of the `Location` class (or instances of any subclass of `Location`). Does that match your understanding?

To your other point, it indeed looks like we have forgotten to include the default shapes in that particular call. I may end up removing that flag in a future release of `brickschema` because as of https://github.com/BrickSchema/Brick/pull/285, the shapes are included in the Brick distribution rather than as a separate file. If you use `load_brick_nightly=True` when creating a `brickschema.Graph`, and call `validate`, you will already be using the default shapes

**Comment by purringeagle** [comment]
Thanks Gabe. That makes sense. 

With regard to matching subclasses of `Location`, I encounter validation errors with values that are not immediate subclasses of `Location`. For instance, validation of the following ttl:
```
@prefix brick: <https://brickschema.org/schema/Brick#> .
@prefix myn: <mynamespace:org/test/> .

myn:Floor1 a brick:Floor .

myn:Room1 a brick:Room ;
    brick:hasLocation myn:Basement1 .

myn:Basement1 a brick:Basement .
```

yields this validation error:
```
Validation Report
Conforms: False
Results (1):
Constraint Violation in ClassConstraintComponent (http://www.w3.org/ns/shacl#ClassConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:class brick:Location ; sh:message Literal("Property hasLocation has object with incorrect type") ; 
sh:path brick:hasLocation ]
        Focus Node: myn:Room1
        Value Node: myn:Basement1
        Result Path: brick:hasLocation
        Message: Property hasLocation has object with incorrect type
```

However, validation passes if I change the ttl to the following (where myn:Room1 brick:hasLocation myn:Floor1):
```
@prefix brick: <https://brickschema.org/schema/Brick#> .
@prefix myn: <mynamespace:org/test/> .

myn:Basement1 a brick:Basement .

myn:Room1 a brick:Room ;
    brick:hasLocation myn:Floor1 .

myn:Floor1 a brick:Floor .
```

Given that `Basement` is a subclass of `Floor` (https://brickschema.org/ontology/1.2/classes/Basement), I was expecting the validation to pass.  Does that sound right to you?

**Comment by gtfierro** [comment]
It's can be a bit of a subtle issue, but this is (perhaps annoyingly) correct behavior. You need to run a "reasoner" to tell the graph that because Basement is a subclass of Floor and floor is a subclass of Location, then any instance of basement is also a Location. I've written up a high-level explanation of this here: https://docs.brickschema.org/lifecycle/inference.html

If you are using the Brickschema package, it is luckily easy to do:

```python
import brickschema
g = brickschema.Graph(load_brick_nightly=True)
g.load_file("your ttl file here")
g.expand("owlrl")
valid, _, report = g.validate()
assert valid, report
```

**Comment by purringeagle** [comment]
Perfect, thanks!
